import java.util.ArrayList;

public class Road {
    //fields
    private ArrayList<Station> totalStations;

    //constructor
    public Road() {
        totalStations = new ArrayList<Station>();
    }

    //METHODS

    /**
     * Adds the passenger to a station's waiting array list based on the passenger's starting location
     * @param a the passenger being added
     */
    public void addPassenger(Passenger a) {
        for(int j = 0; j < totalStations.size(); j++) {
            if(a.getStart() == totalStations.get(j).getNumber()) {
                totalStations.get(j).getWaiting().add(a); 
            }
                        
        }
    }

    /**
     * Adds car to a station's array list of current cars based ont he car's starting location
     * @param a the car being added
     */
    public void addCar(Car a) {
        for(int l = 0; l < totalStations.size(); l++) {
            if(a.getStart() == totalStations.get(l).getNumber()) {
                totalStations.get(l).getDepot().add(a);
            }
        }
    }

    /**
     * Adds the station to the list of all stations on the road
     * @param a the station being added
     */
    public void addStation(Station a) {
        totalStations.add(a);
    }


/**
 * First, drops off and picks up passengers at each station.
 * Then, moves each car to the next station in the direction it's headed by removing the car 
 * from its current station and adding it to the next station.
 * Then, updates the Car's internal location by 1
 */
    public void moveAllCars() {
         //dropping off and picking up passengers
                for(int p = 0; p < totalStations.size(); p++) { 
                    totalStations.get(p).dropOff();
                    totalStations.get(p).pickUp();
                }
        
        

        //removing each car going left from current station and adding to next staion
        for(int m = 0; m < totalStations.size(); m++) {
            Station s = totalStations.get(m);
            for(int n = 0; n < s.getDepot().size(); n++) {
                Car c = s.getDepot().get(n);
                if(c.getFinished() == false && c.getDirection() == 0 && s.getNumber()-1 != 0) { //only moving cars going left
                    totalStations.get(m-1).getDepot().add(c); //adding car to next station
                    s.getDepot().remove(c); //remove car from the station its currently at
                    n--;
                }
                
            }
        }
        //repeating same process for cars going right
        for(int m = totalStations.size() - 1; m >= 0; m--) {
            Station s = totalStations.get(m);    
            for(int p = 0; p < s.getDepot().size(); p++) {
                Car c = s.getDepot().get(p);
                if(c.getFinished() == false && c.getDirection() == 1 && s.getNumber() != 32) { //repeating for cars going right 
                    totalStations.get(m+1).getDepot().add(c); //adding car to next station
                    s.getDepot().remove(c); //remove car from the station its currently at
                    p--;
                }
            }
        }
        //Moving all cars' location by 1
                for(int i = 0; i < totalStations.size(); i++) {
                    for(int k = 0; k < totalStations.get(i).getDepot().size(); k++) {
                        totalStations.get(i).getDepot().get(k).moveCar();
                    }
                }
    }


    
    /**
     * Prints all relevant information for each station (including passengers waiting and current
     * cars) using the toString method. Also prints relevant information for every car(including 
     * its current passengers).
     */
    public void printInfo() {
        for(int b = 0; b < totalStations.size(); b++) {
            System.out.println(totalStations.get(b).toString());
        }
        for(int f = 0; f < totalStations.size(); f++) {
            for(int g = 0; g < totalStations.get(f).getDepot().size(); g++) {
                System.out.println(totalStations.get(f).getDepot().get(g).toString());
            }            
        }
    }
    
    /**
     * Tallys up all the revenue each passenger has generated
     * @return the total revenue generated by all passengers
     */
    public int calculateRevenue() {
        int totalCount = 0;
        for(int i = 0; i < totalStations.size(); i++) {
            for(int j = 0; j < totalStations.get(i).getDepot().size(); j++) {
                totalCount += totalStations.get(i).getDepot().get(j).getRevenue();
            }
        }
        return totalCount;
    }

    /**
     * tallys up all the miles the cars have driven together
     * @return total number of miles the cars have driven combined
     */
    public int calculateMiles() {
        int totalMiles = 0;
        for(int i = 0; i < totalStations.size(); i++) {
            for(int j = 0; j < totalStations.get(i).getDepot().size(); j++) {
                totalMiles += totalStations.get(i).getDepot().get(j).getMilesDriven();
            }
        }
        return totalMiles;
    }


}